

import javax.swing.JOptionPane;
import java.text.*;
import java.util.Calendar;
import java.awt.Color;




/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ARJAY
 */
public class home extends javax.swing.JFrame {

    String iTax, iSubTotal, iTotal,iChange;
    double [] itemcost = new double[20],ipayment = new double[20];
    
    /**
     * Creates new form home
     */
    public home() {
        initComponents();
    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jtxtTax = new javax.swing.JTextField();
        jtxtSubTotal = new javax.swing.JTextField();
        jtxtTotal = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jbtnPayment = new javax.swing.JButton();
        jtxtPayment = new javax.swing.JTextField();
        jtxtChange = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        btnPrint = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jTxtAmericano = new javax.swing.JTextField();
        jTxtBlack = new javax.swing.JTextField();
        jTxtLatte = new javax.swing.JTextField();
        jTxtCappuccino = new javax.swing.JTextField();
        jChkAmericano = new javax.swing.JCheckBox();
        jChkBlack = new javax.swing.JCheckBox();
        jChkLatte = new javax.swing.JCheckBox();
        jChkCappuccino = new javax.swing.JCheckBox();
        jChkMacchiato = new javax.swing.JCheckBox();
        jChkMocha = new javax.swing.JCheckBox();
        jChkExpresso = new javax.swing.JCheckBox();
        jChkIrish = new javax.swing.JCheckBox();
        jTxtMacchiato = new javax.swing.JTextField();
        jTxtIrish = new javax.swing.JTextField();
        jTxtExpresso = new javax.swing.JTextField();
        jTxtMocha = new javax.swing.JTextField();
        jChkFrappucino = new javax.swing.JCheckBox();
        jTxtFrappucino = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtReceipt = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jbtnTotal = new javax.swing.JButton();
        jbtnReset = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(14, 14, 14, 14, new java.awt.Color(255, 255, 102)));
        jPanel1.setForeground(new java.awt.Color(255, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxtTax.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtTax.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtTax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTaxActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtTax, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 100, 30));

        jtxtSubTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtSubTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtSubTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtSubTotalActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtSubTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 100, 30));

        jtxtTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtTotal.setForeground(new java.awt.Color(204, 0, 0));
        jtxtTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTotalActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 100, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Tax");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Sub Total");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Total");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        jbtnPayment.setBackground(new java.awt.Color(153, 255, 153));
        jbtnPayment.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jbtnPayment.setText("Payment");
        jbtnPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPaymentActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, 30));

        jtxtPayment.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jtxtPayment.setForeground(new java.awt.Color(153, 153, 153));
        jtxtPayment.setText("Pay Amount");
        jtxtPayment.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtPaymentFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxtPaymentFocusLost(evt);
            }
        });
        jtxtPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtPaymentActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 90, 30));

        jtxtChange.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jtxtChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtChangeActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 90, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("Change");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, -1, -1));

        btnPrint.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/print.png"))); // NOI18N
        btnPrint.setText("Print");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        jPanel1.add(btnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 109, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 530, 450, 160));

        jPanel2.setBackground(new java.awt.Color(255, 255, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(14, 14, 14, 14, new java.awt.Color(255, 255, 102)));
        jPanel2.setForeground(new java.awt.Color(153, 51, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTxtAmericano.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtAmericano.setText("0");
        jTxtAmericano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtAmericanoActionPerformed(evt);
            }
        });
        jTxtAmericano.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtAmericanoKeyTyped(evt);
            }
        });
        jPanel2.add(jTxtAmericano, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 39, -1));

        jTxtBlack.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtBlack.setText("0");
        jTxtBlack.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtBlackKeyTyped(evt);
            }
        });
        jPanel2.add(jTxtBlack, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 41, -1));

        jTxtLatte.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtLatte.setText("0");
        jTxtLatte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtLatteActionPerformed(evt);
            }
        });
        jTxtLatte.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtLatteKeyTyped(evt);
            }
        });
        jPanel2.add(jTxtLatte, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, 41, -1));

        jTxtCappuccino.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtCappuccino.setText("0");
        jTxtCappuccino.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtCappuccinoKeyTyped(evt);
            }
        });
        jPanel2.add(jTxtCappuccino, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, 40, -1));

        jChkAmericano.setIcon(new javax.swing.ImageIcon(getClass().getResource("/americanoo.png"))); // NOI18N
        jChkAmericano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkAmericanoActionPerformed(evt);
            }
        });
        jPanel2.add(jChkAmericano, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 36, 160, 81));

        jChkBlack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bkackk.png"))); // NOI18N
        jChkBlack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkBlackActionPerformed(evt);
            }
        });
        jPanel2.add(jChkBlack, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 160, 81));

        jChkLatte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lattee.png"))); // NOI18N
        jChkLatte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkLatteActionPerformed(evt);
            }
        });
        jPanel2.add(jChkLatte, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 160, 87));

        jChkCappuccino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cappuccino.png"))); // NOI18N
        jChkCappuccino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkCappuccinoActionPerformed(evt);
            }
        });
        jPanel2.add(jChkCappuccino, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 160, 90));

        jChkMacchiato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/macchiato.png"))); // NOI18N
        jChkMacchiato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkMacchiatoActionPerformed(evt);
            }
        });
        jPanel2.add(jChkMacchiato, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 160, 90));

        jChkMocha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mocha.png"))); // NOI18N
        jChkMocha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkMochaActionPerformed(evt);
            }
        });
        jPanel2.add(jChkMocha, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, 160, 90));

        jChkExpresso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/espresso.png"))); // NOI18N
        jChkExpresso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkExpressoActionPerformed(evt);
            }
        });
        jPanel2.add(jChkExpresso, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 160, 80));

        jChkIrish.setIcon(new javax.swing.ImageIcon(getClass().getResource("/irish.png"))); // NOI18N
        jChkIrish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkIrishActionPerformed(evt);
            }
        });
        jPanel2.add(jChkIrish, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, 160, 90));

        jTxtMacchiato.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtMacchiato.setText("0");
        jTxtMacchiato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtMacchiatoActionPerformed(evt);
            }
        });
        jTxtMacchiato.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtMacchiatoKeyTyped(evt);
            }
        });
        jPanel2.add(jTxtMacchiato, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 40, -1));

        jTxtIrish.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtIrish.setText("0");
        jTxtIrish.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtIrishKeyTyped(evt);
            }
        });
        jPanel2.add(jTxtIrish, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 330, 40, -1));

        jTxtExpresso.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtExpresso.setText("0");
        jTxtExpresso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtExpressoKeyTyped(evt);
            }
        });
        jPanel2.add(jTxtExpresso, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 40, -1));

        jTxtMocha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtMocha.setText("0");
        jTxtMocha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtMochaKeyTyped(evt);
            }
        });
        jPanel2.add(jTxtMocha, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, 40, -1));

        jChkFrappucino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frap.png"))); // NOI18N
        jChkFrappucino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkFrappucinoActionPerformed(evt);
            }
        });
        jPanel2.add(jChkFrappucino, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 160, 90));

        jTxtFrappucino.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtFrappucino.setText("0");
        jTxtFrappucino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtFrappucinoActionPerformed(evt);
            }
        });
        jTxtFrappucino.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtFrappucinoKeyTyped(evt);
            }
        });
        jPanel2.add(jTxtFrappucino, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 430, 40, -1));

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Tokyo", 1, 12)); // NOI18N
        jLabel1.setText("Americano");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tokyo", 1, 10)); // NOI18N
        jLabel2.setText("Black");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tokyo", 1, 10)); // NOI18N
        jLabel3.setText("Irish");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 380, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tokyo", 1, 10)); // NOI18N
        jLabel4.setText("Macchiato");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tokyo", 1, 10)); // NOI18N
        jLabel8.setText("Espresso");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tokyo", 1, 10)); // NOI18N
        jLabel9.setText("Frappuccino");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 480, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tokyo", 1, 10)); // NOI18N
        jLabel10.setText("Latte");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tokyo", 1, 10)); // NOI18N
        jLabel11.setText("Cappuccino");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tokyo", 1, 10)); // NOI18N
        jLabel12.setText("Mocha");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 640, 540));

        jPanel3.setBackground(new java.awt.Color(255, 255, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(14, 14, 14, 14, new java.awt.Color(255, 255, 102)));
        jPanel3.setForeground(new java.awt.Color(255, 204, 204));

        jtxtReceipt.setColumns(20);
        jtxtReceipt.setRows(5);
        jScrollPane1.setViewportView(jtxtReceipt);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 10, -1, 510));

        jPanel4.setBackground(new java.awt.Color(255, 255, 153));
        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(14, 14, 14, 14, new java.awt.Color(255, 255, 102)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnTotal.setBackground(new java.awt.Color(255, 153, 153));
        jbtnTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnTotal.setText("Total");
        jbtnTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTotalActionPerformed(evt);
            }
        });
        jPanel4.add(jbtnTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 109, 52));

        jbtnReset.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Reset.png"))); // NOI18N
        jbtnReset.setText("Reset");
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });
        jPanel4.add(jbtnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 109, 52));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/close Jframe.png"))); // NOI18N
        jButton4.setText("Exit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, 108, 52));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 560, 640, 130));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coffee.jpg"))); // NOI18N
        jLabel13.setText("jLabel13");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        jTxtAmericano.setEnabled(false);
        jTxtBlack.setEnabled(false);
        jTxtLatte.setEnabled(false);
        jTxtCappuccino.setEnabled(false);
        jTxtMacchiato.setEnabled(false);
        jTxtMocha.setEnabled(false);
        jTxtExpresso.setEnabled(false);
        jTxtIrish.setEnabled(false);
        jTxtFrappucino.setEnabled(false);
        jtxtPayment.setEnabled(false);
        jtxtChange.setEnabled(false);
        jtxtTax.setText(null);
        jtxtSubTotal.setText(null);
        jtxtTotal.setText(null);
    }//GEN-LAST:event_formWindowActivated

    private void jChkAmericanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkAmericanoActionPerformed
        // TODO add your handling code here:
        if ( jChkAmericano.isSelected())
        {
            jTxtAmericano.setEnabled(true);
            jTxtAmericano.setText("");
            jTxtAmericano.requestFocus();
        }
        else
        {
        jTxtAmericano.setEnabled(false);
        jTxtAmericano.setText("0");
        }
    }//GEN-LAST:event_jChkAmericanoActionPerformed

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
        // TODO add your handling code here:
        jTxtAmericano.setEnabled(false);
        jTxtBlack.setEnabled(false);
        jTxtLatte.setEnabled(false);
        jTxtCappuccino.setEnabled(false);
        jTxtMacchiato.setEnabled(false);
        jTxtMocha.setEnabled(false);
        jTxtIrish.setEnabled(false);
        jTxtExpresso.setEnabled(false);
        jTxtFrappucino.setEnabled(false);
         jtxtPayment.setEnabled(false);
        
        
        jTxtAmericano.setText("0");
        jTxtBlack.setText("0");
        jTxtLatte.setText("0");
        jTxtCappuccino.setText("0");
        jTxtMacchiato.setText("0");
        jTxtMocha.setText("0");
        jTxtIrish.setText("0");
        jTxtExpresso.setText("0");
        jTxtFrappucino.setText("0");
        jtxtPayment.setText("Pay Amount");
        
        
        jChkAmericano.setSelected(false);
        jChkBlack.setSelected(false);
        jChkLatte.setSelected(false);
        jChkCappuccino.setSelected(false);
        jChkMacchiato.setSelected(false);
        jChkMocha.setSelected(false);
        jChkIrish.setSelected(false);
        jChkExpresso.setSelected(false);
        jChkFrappucino.setSelected(false);
        
        
        jtxtTax.setText(null);
        jtxtSubTotal.setText(null);
        jtxtTotal.setText(null);
        jtxtReceipt.setText(null);
        jtxtChange.setText(null);
    }//GEN-LAST:event_jbtnResetActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        // TODO add your handling code here:
    try{
       jtxtReceipt.print();
    }    
    catch(java.awt.print.PrinterException e){
        System.err.format("No printer found", e.getMessage());
    }
    }//GEN-LAST:event_btnPrintActionPerformed

    private void jChkBlackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkBlackActionPerformed
        // TODO add your handling code here:
        if ( jChkBlack.isSelected())
        {
            jTxtBlack.setEnabled(true);
            jTxtBlack.setText("");
            jTxtBlack.requestFocus();
        }
        else
        {
        jTxtBlack.setEnabled(false);
        jTxtBlack.setText("0");
        }
    }//GEN-LAST:event_jChkBlackActionPerformed

    private void jChkLatteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkLatteActionPerformed
        // TODO add your handling code here:
         if ( jChkLatte.isSelected())
        {
            jTxtLatte.setEnabled(true);
            jTxtLatte.setText("");
            jTxtLatte.requestFocus();
        }
        else
        {
        jTxtLatte.setEnabled(false);
        jTxtLatte.setText("0");
        }
    }//GEN-LAST:event_jChkLatteActionPerformed

    private void jChkCappuccinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkCappuccinoActionPerformed
        // TODO add your handling code here:
         if ( jChkCappuccino.isSelected())
        {
            jTxtCappuccino.setEnabled(true);
            jTxtCappuccino.setText("");
            jTxtCappuccino.requestFocus();
        }
        else
        {
        jTxtCappuccino.setEnabled(false);
        jTxtCappuccino.setText("0");
        }
    }//GEN-LAST:event_jChkCappuccinoActionPerformed

    private void jbtnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTotalActionPerformed
        // TODO add your handling code here:
        
            jtxtPayment.setEnabled(true);
            
       
         
        itemcost[0]= Double.parseDouble(jTxtAmericano.getText()) *54;
        itemcost[1]= Double.parseDouble(jTxtBlack.getText()) *35;
        itemcost[2]= Double.parseDouble(jTxtLatte.getText()) *60;
        itemcost[3]= Double.parseDouble(jTxtCappuccino.getText())*65;
        itemcost[4]= Double.parseDouble(jTxtMacchiato.getText())*70;
        itemcost[5]= Double.parseDouble(jTxtMocha.getText())*68;
        itemcost[6]= Double.parseDouble(jTxtExpresso.getText())*60;
        itemcost[7]= Double.parseDouble(jTxtIrish.getText())*79;
        itemcost[8]= Double.parseDouble(jTxtFrappucino.getText()) *65;
        
        itemcost[9] = itemcost[0] + itemcost[1] + itemcost[2] + itemcost[3] + itemcost[4] + itemcost[5] + itemcost[6] + itemcost[7] + itemcost[8];
        
       
             
        
        
        iTax = String.format("₱ %.2f", itemcost[9]/ 100);
        iSubTotal = String.format("₱ %.2f", itemcost[9]);
        iTotal = String.format("₱ %.2f", itemcost[9] + (itemcost[9]/ 100)) ;
        
        jtxtTax.setText(iTax);
        jtxtSubTotal.setText(iSubTotal);
        jtxtTotal.setText(iTotal);
        
        
      
        
         
        
    }//GEN-LAST:event_jbtnTotalActionPerformed

    private void jtxtTaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTaxActionPerformed

    private void jtxtSubTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtSubTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtSubTotalActionPerformed

    private void jtxtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTotalActionPerformed
   
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int a=JOptionPane.showConfirmDialog(null,"Do you really want to exit?","Select",JOptionPane.YES_NO_OPTION) ;
        if (a==0)
        {
            setVisible(false);
            new login().setVisible(true);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTxtAmericanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtAmericanoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTxtAmericanoActionPerformed

    private void jChkMacchiatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkMacchiatoActionPerformed
        // TODO add your handling code here:
        if ( jChkMacchiato.isSelected())
        {
            jTxtMacchiato.setEnabled(true);
            jTxtMacchiato.setText("");
            jTxtMacchiato.requestFocus();
        }
        else
        {
        jTxtMacchiato.setEnabled(false);
        jTxtMacchiato.setText("0");
        }
    }//GEN-LAST:event_jChkMacchiatoActionPerformed

    private void jChkMochaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkMochaActionPerformed
        // TODO add your handling code here:
        if ( jChkMocha.isSelected())
        {
            jTxtMocha.setEnabled(true);
            jTxtMocha.setText("");
            jTxtMocha.requestFocus();
        }
        else
        {
        jTxtMocha.setEnabled(false);
        jTxtMocha.setText("0");
        }
    }//GEN-LAST:event_jChkMochaActionPerformed

    private void jChkExpressoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkExpressoActionPerformed
        // TODO add your handling code here:
        if ( jChkExpresso.isSelected())
        {
            jTxtExpresso.setEnabled(true);
            jTxtExpresso.setText("");
            jTxtExpresso.requestFocus();
        }
        else
        {
        jTxtExpresso.setEnabled(false);
        jTxtExpresso.setText("0");
        }
    }//GEN-LAST:event_jChkExpressoActionPerformed

    private void jChkIrishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkIrishActionPerformed
        // TODO add your handling code here:
        if ( jChkIrish.isSelected())
        {
            jTxtIrish.setEnabled(true);
            jTxtIrish.setText("");
            jTxtIrish.requestFocus();
        }
        else
        {
        jTxtIrish.setEnabled(false);
        jTxtIrish.setText("0");
        }
    }//GEN-LAST:event_jChkIrishActionPerformed

    private void jChkFrappucinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkFrappucinoActionPerformed
        // TODO add your handling code here:
        if ( jChkFrappucino.isSelected())
        {
            jTxtFrappucino.setEnabled(true);
            jTxtFrappucino.setText("");
            jTxtFrappucino.requestFocus();
        }
        else
        {
        jTxtFrappucino.setEnabled(false);
        jTxtFrappucino.setText("0");
        }
    }//GEN-LAST:event_jChkFrappucinoActionPerformed

    private void jTxtFrappucinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtFrappucinoActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jTxtFrappucinoActionPerformed

    private void jTxtAmericanoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtAmericanoKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if (Character.isLetter(c)&&!evt.isAltDown()){
            evt.consume();
        }
    }//GEN-LAST:event_jTxtAmericanoKeyTyped

    private void jTxtBlackKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtBlackKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if (Character.isLetter(c)&&!evt.isAltDown()){
            evt.consume();
        }
    }//GEN-LAST:event_jTxtBlackKeyTyped

    private void jTxtLatteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtLatteKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if (Character.isLetter(c)&&!evt.isAltDown()){
            evt.consume();
        }
    }//GEN-LAST:event_jTxtLatteKeyTyped

    private void jTxtCappuccinoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtCappuccinoKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if (Character.isLetter(c)&&!evt.isAltDown()){
            evt.consume();
        }
    }//GEN-LAST:event_jTxtCappuccinoKeyTyped

    private void jTxtMacchiatoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtMacchiatoKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if (Character.isLetter(c)&&!evt.isAltDown()){
            evt.consume();
        }
    }//GEN-LAST:event_jTxtMacchiatoKeyTyped

    private void jTxtMochaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtMochaKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if (Character.isLetter(c)&&!evt.isAltDown()){
            evt.consume();
        }
    }//GEN-LAST:event_jTxtMochaKeyTyped

    private void jTxtExpressoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtExpressoKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if (Character.isLetter(c)&&!evt.isAltDown()){
            evt.consume();
        }
    }//GEN-LAST:event_jTxtExpressoKeyTyped

    private void jTxtIrishKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtIrishKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if (Character.isLetter(c)&&!evt.isAltDown()){
            evt.consume();
        }
    }//GEN-LAST:event_jTxtIrishKeyTyped

    private void jTxtFrappucinoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtFrappucinoKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if (Character.isLetter(c)&&!evt.isAltDown()){
            evt.consume();
        }
    }//GEN-LAST:event_jTxtFrappucinoKeyTyped

    private void jTxtLatteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtLatteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtLatteActionPerformed

    private void jbtnPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPaymentActionPerformed
       ipayment[1] = Double.parseDouble(jtxtPayment.getText());
       iChange = String.format("₱ %.2f",ipayment[1]-(itemcost[9]+ itemcost[9]/100));
       jtxtChange.setText(iChange);
       
       //Receipt
       
        jtxtReceipt.setEnabled(true);
        
        int refs = 1325 + (int) (Math.random()*4238);
        
        Calendar timer = Calendar.getInstance();
        timer.getTime();
        SimpleDateFormat tTime = new SimpleDateFormat("HH:mm:ss");
        tTime.format(timer.getTime());
        SimpleDateFormat Tdate = new SimpleDateFormat("dd-MMM-yyyy");
        Tdate.format(timer.getTime());
        
        jtxtReceipt.append("\t                       Coffee Shop \n" +
        "Reference: \t\t\t" + refs +
                "\n================================================\t" +
               
                       "\n=================================================\t" +
                "\nAmericano:\t\t\t" + jTxtAmericano.getText() +
                        "\nBlack:\t\t\t" + jTxtBlack.getText() + 
                        "\nLatte:\t\t\t" + jTxtLatte.getText() +
                        "\nCappuccino:\t\t\t" + jTxtCappuccino.getText() +
                        "\nMacchiato:\t\t\t" + jTxtMacchiato.getText() +
                        "\nMocha:\t\t\t" + jTxtMocha.getText() +
                        "\nExpresso:\t\t\t" + jTxtExpresso.getText() +
                        "\nIrish:\t\t\t" + jTxtIrish.getText() +
                        "\nFrappuccino:\t\t\t" + jTxtFrappucino.getText() +
                "\nTax:\t\t\t" + iTax +
                "\nSub Total:\t\t\t" + iSubTotal + 
                "\n=================================================\t" + 
                "\nTotal:\t\t\t" + iTotal +
                "\n=================================================\t" + 
                "\nPayment:\t\t\t" + "₱"+ipayment[1]+
                 "\nChange:\t\t\t"+ iChange +
                "\nDate:" + Tdate.format(timer.getTime()) + 
                        "\t\tTime:" + tTime.format(timer.getTime()) + 
                "\n\n\tThank you for Shopping at Coffee Shop\n");
        
    }//GEN-LAST:event_jbtnPaymentActionPerformed

    private void jtxtChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtChangeActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jtxtChangeActionPerformed

    private void jtxtPaymentFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtPaymentFocusGained
        // TODO add your handling code here:
        if (jtxtPayment.getText().equals("Pay Amount"))
        {
        jtxtPayment.setText("");
        jtxtPayment.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_jtxtPaymentFocusGained

    private void jtxtPaymentFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtPaymentFocusLost
        // TODO add your handling code here:
         if (jtxtPayment.getText().equals(""))
        {
        jtxtPayment.setText("Pay Amount");
        jtxtPayment.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_jtxtPaymentFocusLost

    private void jTxtMacchiatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtMacchiatoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtMacchiatoActionPerformed

    private void jtxtPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtPaymentActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jtxtPaymentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBox jChkAmericano;
    private javax.swing.JCheckBox jChkBlack;
    private javax.swing.JCheckBox jChkCappuccino;
    private javax.swing.JCheckBox jChkExpresso;
    private javax.swing.JCheckBox jChkFrappucino;
    private javax.swing.JCheckBox jChkIrish;
    private javax.swing.JCheckBox jChkLatte;
    private javax.swing.JCheckBox jChkMacchiato;
    private javax.swing.JCheckBox jChkMocha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTxtAmericano;
    private javax.swing.JTextField jTxtBlack;
    private javax.swing.JTextField jTxtCappuccino;
    private javax.swing.JTextField jTxtExpresso;
    private javax.swing.JTextField jTxtFrappucino;
    private javax.swing.JTextField jTxtIrish;
    private javax.swing.JTextField jTxtLatte;
    private javax.swing.JTextField jTxtMacchiato;
    private javax.swing.JTextField jTxtMocha;
    private javax.swing.JButton jbtnPayment;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JButton jbtnTotal;
    private javax.swing.JTextField jtxtChange;
    private javax.swing.JTextField jtxtPayment;
    private javax.swing.JTextArea jtxtReceipt;
    private javax.swing.JTextField jtxtSubTotal;
    private javax.swing.JTextField jtxtTax;
    private javax.swing.JTextField jtxtTotal;
    // End of variables declaration//GEN-END:variables
}
